
INSERT INTO CUSTOMERS (NAME, PHONE, EMAIL, BIRTHDAY)
	VALUES ('Leibniz Hans', '+066233989', 'hans@gmail.com', '1987-10-10');

INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Halogen lights', 400, 12);
INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Roasted beans', 600, 11);
	
INSERT INTO ORDERS (NUMBER, PLACED, CUSTOMER_ID)
	VALUES ('FNR982774', '1999-7-10 10:20:30', (SELECT ID FROM CUSTOMERS WHERE EMAIL = 'reily.trem@ymail.com'));

INSERT INTO ORDERS_PRODUCTS (ORDER_ID, PRODUCT_ID, QUANTITY)
VALUES ((SELECT ID FROM ORDERS WHERE NUMBER = 'FNR982774'),
	   (SELECT ID FROM PRODUCTS WHERE NAME = 'Halogen lights'),
       4);