
INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Hanlogen lights', 400, 12);
INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Roasted beans', 600, 11);
INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Cat food', 1000, 5);
INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Dog food', 1500, 24);
INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Logitech Keyboard', 700, 23);
INSERT INTO PRODUCTS (NAME, WEIGHT, PRICE)
	VALUES ('Logitech Mouse', 500, 24);